version: '3.8'

volumes:
  pgdata:
    driver: local

services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: autocar
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:Z
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d autocar"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 9s
    restart: unless-stopped

  backend:
    build: .
    command: ["npm", "run", "start:prod"]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_NAME: autocar
      SYNCHRONIZE: "false"
      UPLOAD_FOLDER: "uploads"
      ORIGIN: "*" # Change this to your frontend URL
      PORT: "3000"
    volumes:
      - ./uploads:/app/uploads # This maps your local uploads folder to the container
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped