name: Deploy Backend

on:
  push:
    branches: [ preProduction ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Prepare database initialization files
        run: |
          mkdir -p ~/ansible/initdb
          find initdb/ -name "*.sql" -exec cp {} ~/ansible/initdb/ \;
          echo "Copied these SQL files:"
          ls -la ~/ansible/initdb/
          #mkdir -p ~/ansible/initdb
          #cp initdb/mydb_export.sql ~/ansible/initdb/
          #ls -la ~/ansible/initdb/    
          
      - name: Build and Push Docker Image
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          
          docker build -t 192.168.10.20:5000/nestjs-app:$TIMESTAMP .
          docker push 192.168.10.20:5000/nestjs-app:$TIMESTAMP
          
          echo "IMAGE_TAG=$TIMESTAMP" >> $GITHUB_ENV

      - name: Trigger Ansible
        run: |
          ansible-playbook ~/ansible/playbook-backend.yml -i ~/ansible/inventory.ini \
            --extra-vars "image_tag=$IMAGE_TAG" \
            --ask-become-pass  # Password prompt for sudo
