name: Deploy Backend

on:
  push:
    branches: [ preProduction ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push Docker Image
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          
          docker build -t 192.168.10.20:5000/nestjs-app:$TIMESTAMP .
          docker push 192.168.10.20:5000/nestjs-app:$TIMESTAMP
          
          echo "IMAGE_TAG=$TIMESTAMP" >> $GITHUB_ENV

      - name: Trigger Ansible
        run: |
          ansible-playbook playbook-backend.yml -i inventory.ini \
            --extra-vars "image_tag=$TIMESTAMP" \
            --ask-become-pass  # Password prompt for sudo
